/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.vista.prestamo;

import ec.edu.ups.controlador.LibroControlador;
import ec.edu.ups.controlador.PrestamoControlador;
import ec.edu.ups.controlador.UsuarioControlador;
import ec.edu.ups.modelo.Libro;
import ec.edu.ups.modelo.Prestamo;
import ec.edu.ups.modelo.Usuario;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author arpi
 */
public class VentanaDevolverLibro extends javax.swing.JInternalFrame {
    private PrestamoControlador prestamoControlador;
    private UsuarioControlador usuarioControlador;
    private LibroControlador libroControlador;
    /**
     * Creates new form VentanaCrearUsuario
     */
    public VentanaDevolverLibro(PrestamoControlador prestamoControlador, UsuarioControlador usuarioControlador, LibroControlador libroControlador) {
        initComponents();
        this.prestamoControlador = prestamoControlador;
        this.usuarioControlador = usuarioControlador;
        this.libroControlador = libroControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDevolverLibro = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txt_tit_lib = new javax.swing.JTextField();
        btnDevolverLibro = new javax.swing.JButton();
        lblIdUsuario = new javax.swing.JLabel();
        txt_tit_lib1 = new javax.swing.JTextField();
        btnListarPrestamos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Devolver Libro");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblDevolverLibro.setFont(new java.awt.Font("Righteous", 0, 25)); // NOI18N
        lblDevolverLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblDevolverLibro.setText("DEVOLVER LIBRO");

        lblTitulo.setFont(new java.awt.Font("Righteous", 0, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Título:");

        txt_tit_lib.setEditable(false);

        btnDevolverLibro.setBackground(new java.awt.Color(217, 217, 217));
        btnDevolverLibro.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        btnDevolverLibro.setForeground(new java.awt.Color(0, 0, 0));
        btnDevolverLibro.setText("Devolver Libro");
        btnDevolverLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverLibroActionPerformed(evt);
            }
        });

        lblIdUsuario.setFont(new java.awt.Font("Righteous", 0, 20)); // NOI18N
        lblIdUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblIdUsuario.setText("ID Usuario");

        btnListarPrestamos.setBackground(new java.awt.Color(217, 217, 217));
        btnListarPrestamos.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        btnListarPrestamos.setForeground(new java.awt.Color(0, 0, 0));
        btnListarPrestamos.setText("Listar Prestamos Pendientes");
        btnListarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPrestamosActionPerformed(evt);
            }
        });

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Título", "Fecha Prestamo", "Fecha Devolucion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaLibros);

        btnCancel.setBackground(new java.awt.Color(217, 217, 217));
        btnCancel.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 0, 0));
        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tit_lib1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 137, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblDevolverLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btnListarPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tit_lib, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnDevolverLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblDevolverLibro)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_tit_lib1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnListarPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txt_tit_lib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDevolverLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDevolverLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverLibroActionPerformed
        String identificacion = txt_tit_lib1.getText();
        Usuario usuario = new Usuario();
        usuario = usuarioControlador.read(identificacion.trim());
        String titulo = txt_tit_lib.getText();
        Prestamo prestamo = new Prestamo();
        prestamo = prestamoControlador.devolverPrestamo(usuario, titulo);
        
                    prestamoControlador.delete(prestamo.getUsuario(), prestamo.getLibro());
                    JOptionPane.showMessageDialog(this, "Libro devuelto");
                  
            
        //} while (true);
    }//GEN-LAST:event_btnDevolverLibroActionPerformed

    private void btnListarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPrestamosActionPerformed
        String identificacion = txt_tit_lib1.getText();
        Usuario usuario = new Usuario();
        usuario = usuarioControlador.read(identificacion.trim());
        if (usuario == null) {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado");
        }
        else
        {
            DefaultTableModel tabla = (DefaultTableModel) tablaLibros.getModel();
            tabla.setRowCount(0);
            for (Prestamo prestamo : prestamoControlador.list(usuario)) {
                Object[] fila = {prestamo.getLibro().getTitulo(),prestamo.getFechaPrestamo(),prestamo.getFechaDevolucion()};
                tabla.addRow(fila);
            }            
            txt_tit_lib1.setEditable(false);
            txt_tit_lib.setEditable(true);
        }
    }//GEN-LAST:event_btnListarPrestamosActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        txt_tit_lib1.setEditable(true);
        txt_tit_lib1.setText("");
        txt_tit_lib.setEditable(false);
        txt_tit_lib1.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed

    public void cambiarIdioma(Locale locale){
        DefaultTableModel tabla = (DefaultTableModel) tablaLibros.getModel();
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        lblDevolverLibro.setText(mensajes.getString("lblDevolverLibro"));
        lblIdUsuario.setText(mensajes.getString("lblIdUsuario"));
        btnListarPrestamos.setText(mensajes.getString("btnListarPrestamos"));
        lblTitulo.setText(mensajes.getString("titulo"));
        btnDevolverLibro.setText(mensajes.getString("devolverLibro"));
        tabla.setColumnIdentifiers(new String[]{mensajes.getString("titulo")});
        
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDevolverLibro;
    private javax.swing.JButton btnListarPrestamos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDevolverLibro;
    private javax.swing.JLabel lblIdUsuario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tablaLibros;
    private javax.swing.JTextField txt_tit_lib;
    private javax.swing.JTextField txt_tit_lib1;
    // End of variables declaration//GEN-END:variables
}
