/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.BibliotecaControlador;
import ec.edu.ups.interfaces.BibliotecaListener;
import ec.edu.ups.modelo.Biblioteca;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author karen
 */
public class VentanaBuscarBiblioteca extends javax.swing.JInternalFrame {
    private BibliotecaControlador bibliotecaControlador;
    private int codigo;
    private BibliotecaListener bibliotecaListener;
    /**
     * Creates new form BuscarBiblioteca
     */
    public VentanaBuscarBiblioteca(BibliotecaControlador bibliotecaControlador,int codigo) {
        initComponents();
        this.bibliotecaControlador = bibliotecaControlador;
        this.codigo=codigo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBuscarBiblio = new javax.swing.JPanel();
        lblCodigoBB = new javax.swing.JLabel();
        txtCodigoBB = new javax.swing.JTextField();
        btnBuscarBB = new javax.swing.JButton();
        btnLimpiarBB = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblNombreBB = new javax.swing.JLabel();
        lblDireccionBB = new javax.swing.JLabel();
        lblTelefonoBB = new javax.swing.JLabel();
        txtTelefonoBB = new javax.swing.JTextField();
        txtDireccionBB = new javax.swing.JTextField();
        txtNombreBB = new javax.swing.JTextField();
        lblBuscarBiliotecaBB = new javax.swing.JLabel();

        panelBuscarBiblio.setBackground(new java.awt.Color(51, 51, 51));
        panelBuscarBiblio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lblCodigoBB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblCodigoBB.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoBB.setText("Código");

        btnBuscarBB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnBuscarBB.setText("Buscar");
        btnBuscarBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarBBActionPerformed(evt);
            }
        });

        btnLimpiarBB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnLimpiarBB.setText("Limpiar Búsqueda");
        btnLimpiarBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarBBActionPerformed(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        lblNombreBB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreBB.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreBB.setText("Nombre:");

        lblDireccionBB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDireccionBB.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccionBB.setText("Dirección:");

        lblTelefonoBB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTelefonoBB.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefonoBB.setText("Telefono:");

        txtTelefonoBB.setEnabled(false);

        txtDireccionBB.setEnabled(false);

        txtNombreBB.setEnabled(false);

        lblBuscarBiliotecaBB.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        lblBuscarBiliotecaBB.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscarBiliotecaBB.setText("Buscar Biblioteca");

        javax.swing.GroupLayout panelBuscarBiblioLayout = new javax.swing.GroupLayout(panelBuscarBiblio);
        panelBuscarBiblio.setLayout(panelBuscarBiblioLayout);
        panelBuscarBiblioLayout.setHorizontalGroup(
            panelBuscarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarBiblioLayout.createSequentialGroup()
                .addGroup(panelBuscarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarBiblioLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(panelBuscarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBuscarBiblioLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnAceptar)
                                .addGap(65, 65, 65)
                                .addComponent(btnLimpiarBB))
                            .addGroup(panelBuscarBiblioLayout.createSequentialGroup()
                                .addGroup(panelBuscarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreBB)
                                    .addComponent(lblDireccionBB)
                                    .addComponent(lblTelefonoBB))
                                .addGap(18, 18, 18)
                                .addGroup(panelBuscarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDireccionBB, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreBB, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefonoBB, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelBuscarBiblioLayout.createSequentialGroup()
                                .addComponent(lblCodigoBB)
                                .addGap(29, 29, 29)
                                .addComponent(txtCodigoBB, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnBuscarBB))))
                    .addGroup(panelBuscarBiblioLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblBuscarBiliotecaBB)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        panelBuscarBiblioLayout.setVerticalGroup(
            panelBuscarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarBiblioLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(lblBuscarBiliotecaBB)
                .addGap(18, 18, 18)
                .addGroup(panelBuscarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoBB)
                    .addComponent(txtCodigoBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarBB))
                .addGap(18, 18, 18)
                .addGroup(panelBuscarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreBB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBuscarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionBB)
                    .addComponent(txtDireccionBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBuscarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoBB)
                    .addComponent(txtTelefonoBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panelBuscarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarBB)
                    .addComponent(btnAceptar))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelBuscarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBuscarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarBBActionPerformed
        Biblioteca biblioteca = new Biblioteca();
        codigo = Integer.parseInt(txtCodigoBB.getText().trim());
        biblioteca = bibliotecaControlador.read(codigo);
        if(biblioteca == null){
            JOptionPane.showMessageDialog(this, "No existe biblioteca");
            txtCodigoBB.setEditable(true);
            txtCodigoBB.setText(" ");
        }else{
            txtDireccionBB.setText(biblioteca.getDireccion());
            txtNombreBB.setText(biblioteca.getNombre());
            txtTelefonoBB.setText(biblioteca.getTelefono());
            txtCodigoBB.setEditable(false);
        }

    }//GEN-LAST:event_btnBuscarBBActionPerformed

    private void btnLimpiarBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarBBActionPerformed
        editar();
    }//GEN-LAST:event_btnLimpiarBBActionPerformed

    public void setBibliotecaListener(BibliotecaListener listener) {
        this.bibliotecaListener = listener;
    }
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        if (bibliotecaListener != null) {
            bibliotecaListener.onBibliotecaSeleccionada(bibliotecaControlador,codigo);
        }
        this.dispose();
        editar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void editar(){
        txtCodigoBB.setEditable(true);
        txtCodigoBB.setText(" ");
        txtNombreBB.setText(" ");
        txtDireccionBB.setText(" ");
        txtTelefonoBB.setText(" ");
    }
    
    public void cambiarIdioma(Locale locale){
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        lblBuscarBiliotecaBB.setText(mensajes.getString("lblBuscarBiliotecaBB"));
        lblCodigoBB.setText(mensajes.getString("codigo"));
        lblNombreBB.setText(mensajes.getString("nombre"));
        lblDireccionBB.setText(mensajes.getString("direccion"));
        lblTelefonoBB.setText(mensajes.getString("telefono"));
        btnBuscarBB.setText(mensajes.getString("buscar"));
        btnLimpiarBB.setText(mensajes.getString("limpiarBusqueda"));
        btnAceptar.setText(mensajes.getString("aceptar"));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscarBB;
    private javax.swing.JButton btnLimpiarBB;
    private javax.swing.JLabel lblBuscarBiliotecaBB;
    private javax.swing.JLabel lblCodigoBB;
    private javax.swing.JLabel lblDireccionBB;
    private javax.swing.JLabel lblNombreBB;
    private javax.swing.JLabel lblTelefonoBB;
    private javax.swing.JPanel panelBuscarBiblio;
    private javax.swing.JTextField txtCodigoBB;
    private javax.swing.JTextField txtDireccionBB;
    private javax.swing.JTextField txtNombreBB;
    private javax.swing.JTextField txtTelefonoBB;
    // End of variables declaration//GEN-END:variables
}
