/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.BibliotecaControlador;
import ec.edu.ups.dao.BibliotecaDAO;
import ec.edu.ups.idao.BibliotecaIDAO;
import ec.edu.ups.vista.biblioteca.*;

/**
 *
 * @author karen
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private VentanaCrearBiblioteca ventanaCrearBiblioteca;
    private VentanaEditarBiblioteca ventanaEditarBiblioteca;
    private VentanaEliminarBiblioteca ventanaEliminarBiblioteca;
    private VentanaBuscarBiblioteca ventanaBuscarBiblioteca;
    private VentanaListarBiblioteca ventanaListarBiblioteca;
    
    private BibliotecaIDAO bibliotecaDAO;
    private BibliotecaControlador bibliotecaControlador;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        bibliotecaDAO = new BibliotecaDAO();
        bibliotecaControlador = new BibliotecaControlador(bibliotecaDAO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        crearBibliotecaMenuItem = new javax.swing.JMenuItem();
        editarBibliotecaMenuItem = new javax.swing.JMenuItem();
        eliminarBibliotecaMenuItem = new javax.swing.JMenuItem();
        buscarBibliotecaMenuItem = new javax.swing.JMenuItem();
        listarBibliotecaMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Biblioteca");

        crearBibliotecaMenuItem.setMnemonic('o');
        crearBibliotecaMenuItem.setText("Crear");
        crearBibliotecaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearBibliotecaMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(crearBibliotecaMenuItem);

        editarBibliotecaMenuItem.setMnemonic('s');
        editarBibliotecaMenuItem.setText("Editar");
        editarBibliotecaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBibliotecaMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(editarBibliotecaMenuItem);

        eliminarBibliotecaMenuItem.setMnemonic('a');
        eliminarBibliotecaMenuItem.setText("Eliminar");
        eliminarBibliotecaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBibliotecaMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(eliminarBibliotecaMenuItem);

        buscarBibliotecaMenuItem.setMnemonic('x');
        buscarBibliotecaMenuItem.setText("Buscar");
        buscarBibliotecaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBibliotecaMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(buscarBibliotecaMenuItem);

        listarBibliotecaMenuItem.setText("Listar");
        listarBibliotecaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBibliotecaMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(listarBibliotecaMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Libro");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Cliente");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        jMenu3.setText("Prestamo");
        menuBar.add(jMenu3);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBibliotecaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBibliotecaMenuItemActionPerformed
        if(ventanaBuscarBiblioteca==null)
            ventanaBuscarBiblioteca = new VentanaBuscarBiblioteca(bibliotecaControlador);
        if(!ventanaBuscarBiblioteca.isVisible()){
            ventanaBuscarBiblioteca.setVisible(true);
            desktopPane.add(ventanaBuscarBiblioteca);
        }
    }//GEN-LAST:event_buscarBibliotecaMenuItemActionPerformed

    private void crearBibliotecaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearBibliotecaMenuItemActionPerformed
        if(ventanaCrearBiblioteca==null)
            ventanaCrearBiblioteca = new VentanaCrearBiblioteca(bibliotecaControlador);
        if(!ventanaCrearBiblioteca.isVisible()){
            ventanaCrearBiblioteca.setVisible(true);
            desktopPane.add(ventanaCrearBiblioteca);
        }
    }//GEN-LAST:event_crearBibliotecaMenuItemActionPerformed

    private void listarBibliotecaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBibliotecaMenuItemActionPerformed
        if(ventanaListarBiblioteca==null)
            ventanaListarBiblioteca = new VentanaListarBiblioteca(bibliotecaControlador);
        if(!ventanaListarBiblioteca.isVisible()){
            ventanaListarBiblioteca.setVisible(true);
            ventanaListarBiblioteca.cargarDatos();
            desktopPane.add(ventanaListarBiblioteca);
        }
    }//GEN-LAST:event_listarBibliotecaMenuItemActionPerformed

    private void eliminarBibliotecaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBibliotecaMenuItemActionPerformed
        if(ventanaEliminarBiblioteca==null)
            ventanaEliminarBiblioteca = new VentanaEliminarBiblioteca(bibliotecaControlador);
        if(!ventanaEliminarBiblioteca.isVisible()){
            ventanaEliminarBiblioteca.setVisible(true);
            desktopPane.add(ventanaEliminarBiblioteca);
        }
    }//GEN-LAST:event_eliminarBibliotecaMenuItemActionPerformed

    private void editarBibliotecaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBibliotecaMenuItemActionPerformed
        if(ventanaEditarBiblioteca==null)
            ventanaEditarBiblioteca = new VentanaEditarBiblioteca(bibliotecaControlador);
        if(!ventanaEditarBiblioteca.isVisible()){
            ventanaEditarBiblioteca.setVisible(true);
            desktopPane.add(ventanaEditarBiblioteca);
        }
    }//GEN-LAST:event_editarBibliotecaMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem buscarBibliotecaMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem crearBibliotecaMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem editarBibliotecaMenuItem;
    private javax.swing.JMenuItem eliminarBibliotecaMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listarBibliotecaMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
