/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.BibliotecaControlador;
import ec.edu.ups.controlador.LibroControlador;
import ec.edu.ups.interfaces.BibliotecaListener;
import ec.edu.ups.modelo.Biblioteca;
import javax.swing.JOptionPane;

/**
 *
 * @author karen
 */
public class VentanaSeleccionarBiblioteca extends javax.swing.JInternalFrame implements BibliotecaListener{
    private VentanaBuscarBiblioteca ventanaBuscarBiblioteca;
    private int codigo;
    private BibliotecaControlador bibliotecaControlador;
    private LibroControlador libroControlador;
    /**
     * Creates new form VentanaSeleccionarBiblioteca
     */
    public VentanaSeleccionarBiblioteca(BibliotecaControlador bibliotecaControlador, LibroControlador libroControlador) {
        initComponents();
        this.bibliotecaControlador = bibliotecaControlador;
        this.libroControlador = libroControlador;
        codigo=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblSeleccionarBiblio = new javax.swing.JLabel();
        txtNombreBiblio = new javax.swing.JTextField();
        btnSeleccionarBiblioteca = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        crearLibroMenuItem = new javax.swing.JMenuItem();
        actualizarLibroMenuItem = new javax.swing.JMenuItem();
        buscarLibroMenuItem = new javax.swing.JMenuItem();
        eliminarLibroMenuItem = new javax.swing.JMenuItem();
        listarLibroMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        lblSeleccionarBiblio.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        lblSeleccionarBiblio.setText("Seleccionar Biblioteca");

        txtNombreBiblio.setEditable(false);
        txtNombreBiblio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSeleccionarBiblioteca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSeleccionarBiblioteca.setText("Seleccionar");
        btnSeleccionarBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarBibliotecaActionPerformed(evt);
            }
        });

        jMenuBar1.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N

        jMenu1.setText("Libros");

        crearLibroMenuItem.setText("Crear");
        jMenu1.add(crearLibroMenuItem);

        actualizarLibroMenuItem.setText("Actualizar");
        jMenu1.add(actualizarLibroMenuItem);

        buscarLibroMenuItem.setText("Buscar");
        jMenu1.add(buscarLibroMenuItem);

        eliminarLibroMenuItem.setText("Eliminar");
        jMenu1.add(eliminarLibroMenuItem);

        listarLibroMenuItem.setText("Listar");
        jMenu1.add(listarLibroMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usuarios");

        jMenuItem6.setText("jMenuItem6");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("jMenuItem7");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("jMenuItem8");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("jMenuItem9");
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Préstamo");

        jMenuItem10.setText("Solicitar Libro");
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Devolver Libro");
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSeleccionarBiblio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreBiblio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionarBiblioteca)
                        .addGap(141, 141, 141)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblSeleccionarBiblio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSeleccionarBiblioteca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarBibliotecaActionPerformed
        if(ventanaBuscarBiblioteca==null){
            ventanaBuscarBiblioteca = new VentanaBuscarBiblioteca(bibliotecaControlador,codigo);
            ventanaBuscarBiblioteca.setBibliotecaListener(this);
        }
            
        if(!ventanaBuscarBiblioteca.isVisible()){
            ventanaBuscarBiblioteca.setVisible(true);
            jDesktopPane1.add(ventanaBuscarBiblioteca);
        }     
    }//GEN-LAST:event_btnSeleccionarBibliotecaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actualizarLibroMenuItem;
    private javax.swing.JButton btnSeleccionarBiblioteca;
    private javax.swing.JMenuItem buscarLibroMenuItem;
    private javax.swing.JMenuItem crearLibroMenuItem;
    private javax.swing.JMenuItem eliminarLibroMenuItem;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSeleccionarBiblio;
    private javax.swing.JMenuItem listarLibroMenuItem;
    private javax.swing.JTextField txtNombreBiblio;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onBibliotecaSeleccionada(BibliotecaControlador bibliotecaControlador, int codigo) {
        Biblioteca biblioteca = new Biblioteca();
        biblioteca=bibliotecaControlador.read(codigo);
        txtNombreBiblio.setText(biblioteca.getNombre());
        this.bibliotecaControlador=bibliotecaControlador;
    }
}
