/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.vista.biblioteca;

import ec.edu.ups.controlador.BibliotecaControlador;
import ec.edu.ups.modelo.Administrador;
import ec.edu.ups.modelo.Biblioteca;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karen
 */
public class VentanaCrudBiblioteca extends javax.swing.JInternalFrame {
    
    
    private BibliotecaControlador bibliotecaControlador;
    /**
     * Creates new form CrudBiblioteca
     */
    public VentanaCrudBiblioteca(BibliotecaControlador bibliotecaControlador) {
        initComponents();
        this.bibliotecaControlador = bibliotecaControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelEditarDatosBiblio = new javax.swing.JTabbedPane();
        panelInicio = new javax.swing.JPanel();
        lblIngresoAdmin = new javax.swing.JLabel();
        lblAdmBiblio = new javax.swing.JLabel();
        lblUsuarioI = new javax.swing.JLabel();
        lblContrasenaI = new javax.swing.JLabel();
        txtUsuarioAdm = new javax.swing.JTextField();
        txtContrasenaAdm = new javax.swing.JTextField();
        btnAcceder = new javax.swing.JButton();
        panelIngresarDatosBiblio = new javax.swing.JPanel();
        lblCodigoCB = new javax.swing.JLabel();
        lblNombreCB = new javax.swing.JLabel();
        lblDireccionCB = new javax.swing.JLabel();
        lblTelefonoCB = new javax.swing.JLabel();
        txtTlefonoID = new javax.swing.JTextField();
        txtDireccionID = new javax.swing.JTextField();
        txtNombreID = new javax.swing.JTextField();
        txtCodigoID = new javax.swing.JTextField();
        btnCrearBiblioteca = new javax.swing.JButton();
        panelEditarBiblio = new javax.swing.JPanel();
        lblCodigoEDB = new javax.swing.JLabel();
        lblNombreEDB = new javax.swing.JLabel();
        lblDireccionEDB = new javax.swing.JLabel();
        lblTelefonoEDB = new javax.swing.JLabel();
        txtTelefonoED = new javax.swing.JTextField();
        txtDireccionED = new javax.swing.JTextField();
        txtNombreED = new javax.swing.JTextField();
        txtCodigoED = new javax.swing.JTextField();
        btnBuscarEDB = new javax.swing.JButton();
        btnActualizarEDB = new javax.swing.JButton();
        btnCancelarEDB = new javax.swing.JButton();
        panelBuscarBiblio = new javax.swing.JPanel();
        lblCodigoBB = new javax.swing.JLabel();
        txtCodigoBB = new javax.swing.JTextField();
        btnBuscarBB = new javax.swing.JButton();
        panelDatosBiblioBB = new javax.swing.JPanel();
        lblNombreBB = new javax.swing.JLabel();
        lblDireccionBB = new javax.swing.JLabel();
        lblTelefonoBB = new javax.swing.JLabel();
        txtNombreBB = new javax.swing.JTextField();
        txtDireccionBB = new javax.swing.JTextField();
        txtTelefonoBB = new javax.swing.JTextField();
        btnLimpiarBB = new javax.swing.JButton();
        panelEliminarBiblio = new javax.swing.JPanel();
        lblCodigoEB = new javax.swing.JLabel();
        txtCodigoEB = new javax.swing.JTextField();
        btnBuscarEB = new javax.swing.JButton();
        panelDatosBiblioEB = new javax.swing.JPanel();
        lblNombreEB = new javax.swing.JLabel();
        lblDireccionEB = new javax.swing.JLabel();
        lblTelefonoEB = new javax.swing.JLabel();
        txtNombreEB = new javax.swing.JTextField();
        txtDireccionEB = new javax.swing.JTextField();
        txtTelefonoEB = new javax.swing.JTextField();
        btnEliminarEB = new javax.swing.JButton();
        btnCancelarEB = new javax.swing.JButton();
        panelListaBiblio = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBibliotecas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelEditarDatosBiblio.setEnabled(false);
        panelEditarDatosBiblio.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        panelEditarDatosBiblio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEditarDatosBiblioMouseClicked(evt);
            }
        });

        panelInicio.setBackground(new java.awt.Color(51, 51, 51));
        panelInicio.setFocusCycleRoot(true);

        lblIngresoAdmin.setFont(new java.awt.Font("Righteous", 3, 18)); // NOI18N
        lblIngresoAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblIngresoAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngresoAdmin.setText("Ingreso como administrador");

        lblAdmBiblio.setFont(new java.awt.Font("Righteous", 0, 25)); // NOI18N
        lblAdmBiblio.setForeground(new java.awt.Color(255, 255, 255));
        lblAdmBiblio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdmBiblio.setText("ADMINISTRAR BIBLIOTECAS");

        lblUsuarioI.setFont(new java.awt.Font("Righteous", 3, 18)); // NOI18N
        lblUsuarioI.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarioI.setText("Usuario");

        lblContrasenaI.setFont(new java.awt.Font("Righteous", 3, 18)); // NOI18N
        lblContrasenaI.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasenaI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContrasenaI.setText("Contraseña");

        btnAcceder.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 18)); // NOI18N
        btnAcceder.setText("Acceder");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblIngresoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblAdmBiblio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                .addGap(0, 90, Short.MAX_VALUE)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUsuarioI, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContrasenaI, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAcceder)
                    .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtUsuarioAdm)
                        .addComponent(txtContrasenaAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(88, 88, 88))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblAdmBiblio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIngresoAdmin)
                .addGap(18, 18, 18)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioI)
                    .addComponent(txtUsuarioAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasenaI)
                    .addComponent(txtContrasenaAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAcceder)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        panelEditarDatosBiblio.addTab("Inicio", panelInicio);

        panelIngresarDatosBiblio.setBackground(new java.awt.Color(91, 86, 86));
        panelIngresarDatosBiblio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lblCodigoCB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblCodigoCB.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoCB.setText("Código");

        lblNombreCB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblNombreCB.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCB.setText("Nombre");

        lblDireccionCB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblDireccionCB.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccionCB.setText("Dirección");

        lblTelefonoCB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTelefonoCB.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefonoCB.setText("Teléfono");

        btnCrearBiblioteca.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnCrearBiblioteca.setText("Crear");
        btnCrearBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearBibliotecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIngresarDatosBiblioLayout = new javax.swing.GroupLayout(panelIngresarDatosBiblio);
        panelIngresarDatosBiblio.setLayout(panelIngresarDatosBiblioLayout);
        panelIngresarDatosBiblioLayout.setHorizontalGroup(
            panelIngresarDatosBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosBiblioLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(panelIngresarDatosBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrearBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelIngresarDatosBiblioLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccionCB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelIngresarDatosBiblioLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblTelefonoCB, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNombreCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigoCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(panelIngresarDatosBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionID, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreID, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTlefonoID, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoID, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        panelIngresarDatosBiblioLayout.setVerticalGroup(
            panelIngresarDatosBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosBiblioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoCB)
                    .addComponent(txtCodigoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresarDatosBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCB)
                    .addComponent(txtNombreID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresarDatosBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionCB)
                    .addComponent(txtDireccionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresarDatosBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoCB)
                    .addComponent(txtTlefonoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnCrearBiblioteca)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        panelEditarDatosBiblio.addTab("Crear", panelIngresarDatosBiblio);

        panelEditarBiblio.setBackground(new java.awt.Color(91, 86, 86));
        panelEditarBiblio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lblCodigoEDB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblCodigoEDB.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoEDB.setText("Código");

        lblNombreEDB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblNombreEDB.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreEDB.setText("Nombre");

        lblDireccionEDB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblDireccionEDB.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccionEDB.setText("Dirección");

        lblTelefonoEDB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTelefonoEDB.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefonoEDB.setText("Teléfono");

        txtTelefonoED.setEditable(false);

        txtDireccionED.setEditable(false);

        txtNombreED.setEditable(false);

        btnBuscarEDB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnBuscarEDB.setText("Buscar");
        btnBuscarEDB.setToolTipText("");
        btnBuscarEDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEDBActionPerformed(evt);
            }
        });

        btnActualizarEDB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnActualizarEDB.setText("Actualizar");
        btnActualizarEDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEDBActionPerformed(evt);
            }
        });

        btnCancelarEDB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnCancelarEDB.setText("Cancelar");
        btnCancelarEDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEditarBiblioLayout = new javax.swing.GroupLayout(panelEditarBiblio);
        panelEditarBiblio.setLayout(panelEditarBiblioLayout);
        panelEditarBiblioLayout.setHorizontalGroup(
            panelEditarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditarBiblioLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panelEditarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelEditarBiblioLayout.createSequentialGroup()
                        .addGroup(panelEditarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodigoEDB)
                            .addComponent(lblDireccionEDB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreEDB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefonoEDB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEditarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDireccionED, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreED, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoED, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefonoED, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelEditarBiblioLayout.createSequentialGroup()
                        .addComponent(btnActualizarEDB, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarEDB, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(btnBuscarEDB)
                .addGap(32, 32, 32))
        );
        panelEditarBiblioLayout.setVerticalGroup(
            panelEditarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarBiblioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelEditarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoEDB)
                    .addComponent(txtCodigoED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEDB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEditarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEDB)
                    .addComponent(txtNombreED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEditarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionEDB)
                    .addComponent(txtDireccionED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEditarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoEDB)
                    .addComponent(txtTelefonoED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelEditarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarEDB)
                    .addComponent(btnActualizarEDB))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        panelEditarDatosBiblio.addTab("Editar", panelEditarBiblio);

        panelBuscarBiblio.setBackground(new java.awt.Color(91, 86, 86));
        panelBuscarBiblio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Biblioteca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lblCodigoBB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblCodigoBB.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoBB.setText("Código");

        btnBuscarBB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnBuscarBB.setText("Buscar");
        btnBuscarBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarBBActionPerformed(evt);
            }
        });

        panelDatosBiblioBB.setBackground(new java.awt.Color(204, 204, 204));
        panelDatosBiblioBB.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Biblioteca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        lblNombreBB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreBB.setText("Nombre:");

        lblDireccionBB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDireccionBB.setText("Dirección:");

        lblTelefonoBB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelefonoBB.setText("Telefono:");

        txtNombreBB.setEditable(false);
        txtNombreBB.setEnabled(false);

        txtDireccionBB.setEditable(false);
        txtDireccionBB.setEnabled(false);

        txtTelefonoBB.setEditable(false);
        txtTelefonoBB.setEnabled(false);

        javax.swing.GroupLayout panelDatosBiblioBBLayout = new javax.swing.GroupLayout(panelDatosBiblioBB);
        panelDatosBiblioBB.setLayout(panelDatosBiblioBBLayout);
        panelDatosBiblioBBLayout.setHorizontalGroup(
            panelDatosBiblioBBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosBiblioBBLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelDatosBiblioBBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreBB)
                    .addComponent(lblDireccionBB)
                    .addComponent(lblTelefonoBB))
                .addGap(18, 18, 18)
                .addGroup(panelDatosBiblioBBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccionBB, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(txtNombreBB)
                    .addComponent(txtTelefonoBB))
                .addContainerGap())
        );
        panelDatosBiblioBBLayout.setVerticalGroup(
            panelDatosBiblioBBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosBiblioBBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosBiblioBBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreBB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosBiblioBBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionBB)
                    .addComponent(txtDireccionBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosBiblioBBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoBB)
                    .addComponent(txtTelefonoBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnLimpiarBB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnLimpiarBB.setText("Limpiar Búsqueda");
        btnLimpiarBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarBBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarBiblioLayout = new javax.swing.GroupLayout(panelBuscarBiblio);
        panelBuscarBiblio.setLayout(panelBuscarBiblioLayout);
        panelBuscarBiblioLayout.setHorizontalGroup(
            panelBuscarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarBiblioLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(panelBuscarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarBiblioLayout.createSequentialGroup()
                        .addGroup(panelBuscarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelDatosBiblioBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBuscarBiblioLayout.createSequentialGroup()
                                .addComponent(lblCodigoBB)
                                .addGap(29, 29, 29)
                                .addComponent(txtCodigoBB, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(btnBuscarBB))
                    .addGroup(panelBuscarBiblioLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnLimpiarBB)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panelBuscarBiblioLayout.setVerticalGroup(
            panelBuscarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarBiblioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelBuscarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoBB)
                    .addComponent(txtCodigoBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarBB))
                .addGap(18, 18, 18)
                .addComponent(panelDatosBiblioBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiarBB)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        panelEditarDatosBiblio.addTab("Buscar", panelBuscarBiblio);

        panelEliminarBiblio.setBackground(new java.awt.Color(91, 86, 86));
        panelEliminarBiblio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminar Biblioteca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lblCodigoEB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblCodigoEB.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoEB.setText("Código");

        btnBuscarEB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnBuscarEB.setText("Buscar");
        btnBuscarEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEBActionPerformed(evt);
            }
        });

        panelDatosBiblioEB.setBackground(new java.awt.Color(204, 204, 204));
        panelDatosBiblioEB.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Biblioteca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        lblNombreEB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreEB.setText("Nombre:");

        lblDireccionEB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDireccionEB.setText("Dirección:");

        lblTelefonoEB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelefonoEB.setText("Telefono:");

        txtNombreEB.setEnabled(false);

        txtDireccionEB.setEnabled(false);

        txtTelefonoEB.setEnabled(false);

        javax.swing.GroupLayout panelDatosBiblioEBLayout = new javax.swing.GroupLayout(panelDatosBiblioEB);
        panelDatosBiblioEB.setLayout(panelDatosBiblioEBLayout);
        panelDatosBiblioEBLayout.setHorizontalGroup(
            panelDatosBiblioEBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosBiblioEBLayout.createSequentialGroup()
                .addGroup(panelDatosBiblioEBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosBiblioEBLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblNombreEB)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosBiblioEBLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDatosBiblioEBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefonoEB)
                            .addComponent(lblDireccionEB))
                        .addGap(18, 18, 18)))
                .addGroup(panelDatosBiblioEBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccionEB, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(txtNombreEB)
                    .addComponent(txtTelefonoEB))
                .addGap(22, 22, 22))
        );
        panelDatosBiblioEBLayout.setVerticalGroup(
            panelDatosBiblioEBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosBiblioEBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosBiblioEBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreEB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosBiblioEBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionEB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccionEB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosBiblioEBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoEB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoEB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEliminarEB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnEliminarEB.setText("Eliminar");
        btnEliminarEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEBActionPerformed(evt);
            }
        });

        btnCancelarEB.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnCancelarEB.setText("Cancelar");
        btnCancelarEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEliminarBiblioLayout = new javax.swing.GroupLayout(panelEliminarBiblio);
        panelEliminarBiblio.setLayout(panelEliminarBiblioLayout);
        panelEliminarBiblioLayout.setHorizontalGroup(
            panelEliminarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarBiblioLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(panelEliminarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEliminarBiblioLayout.createSequentialGroup()
                        .addComponent(lblCodigoEB)
                        .addGap(29, 29, 29)
                        .addComponent(txtCodigoEB, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnBuscarEB))
                    .addComponent(panelDatosBiblioEB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEliminarBiblioLayout.createSequentialGroup()
                        .addComponent(btnEliminarEB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarEB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        panelEliminarBiblioLayout.setVerticalGroup(
            panelEliminarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarBiblioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelEliminarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoEB)
                    .addComponent(txtCodigoEB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEB))
                .addGap(18, 18, 18)
                .addComponent(panelDatosBiblioEB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEliminarBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarEB)
                    .addComponent(btnEliminarEB))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        panelEditarDatosBiblio.addTab("Eliminar", panelEliminarBiblio);

        panelListaBiblio.setBackground(new java.awt.Color(91, 86, 86));
        panelListaBiblio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        tblBibliotecas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblBibliotecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Dirección", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBibliotecas);

        javax.swing.GroupLayout panelListaBiblioLayout = new javax.swing.GroupLayout(panelListaBiblio);
        panelListaBiblio.setLayout(panelListaBiblioLayout);
        panelListaBiblioLayout.setHorizontalGroup(
            panelListaBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaBiblioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelListaBiblioLayout.setVerticalGroup(
            panelListaBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaBiblioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelEditarDatosBiblio.addTab("Listar", panelListaBiblio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEditarDatosBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelEditarDatosBiblio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearBibliotecaActionPerformed
        int codigo = Integer.parseInt( txtCodigoID.getText().trim());
        String nombre = txtNombreID.getText().trim();
        String direccion = txtDireccionID.getText().trim();
        String telefono= txtTlefonoID.getText().trim();

        bibliotecaControlador.create(codigo, nombre, direccion, telefono);
        JOptionPane.showMessageDialog(this, "Biblioteca creada exitosamente");
        txtCodigoID.setText(" ");
        txtDireccionID.setText(" ");
        txtNombreID.setText(" ");
        txtTlefonoID.setText(" ");
    }//GEN-LAST:event_btnCrearBibliotecaActionPerformed

    private void btnBuscarEDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEDBActionPerformed
        Biblioteca biblioteca = new Biblioteca();
        int codigo = Integer.parseInt(txtCodigoED.getText().trim());
        biblioteca = bibliotecaControlador.read(codigo);
        if(biblioteca == null){
            JOptionPane.showMessageDialog(this, "No existe biblioteca");
        }else{
            txtDireccionED.setText(biblioteca.getDireccion());
            txtNombreED.setText(biblioteca.getNombre());
            txtTelefonoED.setText(biblioteca.getTelefono());
            
            txtDireccionED.setEditable(true);
            txtNombreED.setEditable(true);
            txtTelefonoED.setEditable(true);
            txtCodigoED.setEditable(false);
        }
        
        txtCodigoID.setEditable(false);
    }//GEN-LAST:event_btnBuscarEDBActionPerformed

    private void btnActualizarEDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEDBActionPerformed
        int codigo = Integer.parseInt( txtCodigoED.getText().trim());
        String nombre = txtNombreED.getText().trim();
        String direccion = txtDireccionED.getText().trim();
        String telefono= txtTelefonoED.getText().trim();
        
        Biblioteca biblioteca = bibliotecaControlador.read(codigo);
        if(biblioteca == null){
            JOptionPane.showMessageDialog(this, "No existe biblioteca");
        }else{
            bibliotecaControlador.update(codigo, nombre, direccion, telefono);
            JOptionPane.showMessageDialog(this, "Biblioteca editada correctamente");
        }
        limpiarDatosED();
    }//GEN-LAST:event_btnActualizarEDBActionPerformed

    private void btnCancelarEDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEDBActionPerformed
       limpiarDatosED();
    }//GEN-LAST:event_btnCancelarEDBActionPerformed

    private void btnBuscarBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarBBActionPerformed
        int codigo = Integer.parseInt(txtCodigoBB.getText().trim());
        Biblioteca biblioteca = bibliotecaControlador.read(codigo);
        if(biblioteca == null){
            JOptionPane.showMessageDialog(this, "No existe biblioteca");
            txtCodigoBB.setEditable(true);
            txtCodigoBB.setText(" ");
        }else{
            txtDireccionBB.setText(biblioteca.getDireccion());
            txtNombreBB.setText(biblioteca.getNombre());
            txtTelefonoBB.setText(biblioteca.getTelefono());
            txtCodigoBB.setEditable(false);
        }

        
    }//GEN-LAST:event_btnBuscarBBActionPerformed

    private void btnLimpiarBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarBBActionPerformed
        txtCodigoBB.setEditable(true);
        txtCodigoBB.setText(" ");
        txtNombreBB.setText(" ");
        txtDireccionBB.setText(" ");
        txtTelefonoBB.setText(" ");
    }//GEN-LAST:event_btnLimpiarBBActionPerformed

    private void btnBuscarEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEBActionPerformed
        int codigo = Integer.parseInt(txtCodigoEB.getText().trim());
        Biblioteca biblioteca = new Biblioteca();
        biblioteca = bibliotecaControlador.read(codigo);
        if(biblioteca == null){
            JOptionPane.showMessageDialog(this, "No existe biblioteca");
            txtCodigoEB.setEditable(true);
            txtCodigoEB.setText(" ");
        }else{
            txtDireccionEB.setText(biblioteca.getDireccion());
            txtNombreEB.setText(biblioteca.getNombre());
            txtTelefonoEB.setText(biblioteca.getTelefono());
            txtCodigoEB.setEditable(false);
        }

        
    }//GEN-LAST:event_btnBuscarEBActionPerformed

    private void btnEliminarEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEBActionPerformed
        int codigo = Integer.parseInt(txtCodigoEB.getText().trim());
        Biblioteca biblioteca = new Biblioteca();
        biblioteca = bibliotecaControlador.read(codigo);
        if(biblioteca != null){
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar?");
            if(respuesta == JOptionPane.YES_OPTION){
                bibliotecaControlador.delete(codigo);
                JOptionPane.showMessageDialog(this, "Biblioteca eliminada");
            }

        }
        limpiarDatosEB();
    }//GEN-LAST:event_btnEliminarEBActionPerformed

    private void btnCancelarEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEBActionPerformed
        limpiarDatosEB();
    }//GEN-LAST:event_btnCancelarEBActionPerformed

    private void panelEditarDatosBiblioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditarDatosBiblioMouseClicked
        DefaultTableModel tabla = (DefaultTableModel) tblBibliotecas.getModel();
        tabla.setRowCount(0);
        
        for (Biblioteca biblioteca : bibliotecaControlador.list()) {
            Object[] fila = {biblioteca.getCodigo(),biblioteca.getNombre(),biblioteca.getDireccion(),biblioteca.getTelefono()};
            tabla.addRow(fila);
        }
    }//GEN-LAST:event_panelEditarDatosBiblioMouseClicked

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        String usuario = txtUsuarioAdm.getText().trim();
        String contraseña = txtContrasenaAdm.getText().trim();
        Administrador adm = new Administrador();
        if(usuario.equals(adm.getUsuario()) && contraseña.equals(adm.getContrasena())){
            panelEditarDatosBiblio.setEnabled(true);
            txtUsuarioAdm.setText(" ");
            txtContrasenaAdm.setText(" ");
        }else{
            JOptionPane.showMessageDialog(this, "Usuario o Contraseña incorrectas");
            txtUsuarioAdm.setText(" ");
            txtContrasenaAdm.setText(" ");
        }
    }//GEN-LAST:event_btnAccederActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        panelEditarDatosBiblio.setEnabled(false);
    }//GEN-LAST:event_formInternalFrameClosing
    
    private void limpiarDatosEB(){
        txtCodigoEB.setText(" ");
        txtDireccionEB.setText(" ");
        txtNombreEB.setText(" ");
        txtTelefonoEB.setText(" ");
        txtCodigoEB.setEditable(true);
    }
    
    private void limpiarDatosED (){
        txtCodigoED.setText(" ");
        txtDireccionED.setText(" ");
        txtNombreED.setText(" ");
        txtTelefonoED.setText(" ");
        txtCodigoED.setEditable(true);
        
        txtDireccionED.setEditable(false);
        txtNombreED.setEditable(false);
        txtTelefonoED.setEditable(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnActualizarEDB;
    private javax.swing.JButton btnBuscarBB;
    private javax.swing.JButton btnBuscarEB;
    private javax.swing.JButton btnBuscarEDB;
    private javax.swing.JButton btnCancelarEB;
    private javax.swing.JButton btnCancelarEDB;
    private javax.swing.JButton btnCrearBiblioteca;
    private javax.swing.JButton btnEliminarEB;
    private javax.swing.JButton btnLimpiarBB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdmBiblio;
    private javax.swing.JLabel lblCodigoBB;
    private javax.swing.JLabel lblCodigoCB;
    private javax.swing.JLabel lblCodigoEB;
    private javax.swing.JLabel lblCodigoEDB;
    private javax.swing.JLabel lblContrasenaI;
    private javax.swing.JLabel lblDireccionBB;
    private javax.swing.JLabel lblDireccionCB;
    private javax.swing.JLabel lblDireccionEB;
    private javax.swing.JLabel lblDireccionEDB;
    private javax.swing.JLabel lblIngresoAdmin;
    private javax.swing.JLabel lblNombreBB;
    private javax.swing.JLabel lblNombreCB;
    private javax.swing.JLabel lblNombreEB;
    private javax.swing.JLabel lblNombreEDB;
    private javax.swing.JLabel lblTelefonoBB;
    private javax.swing.JLabel lblTelefonoCB;
    private javax.swing.JLabel lblTelefonoEB;
    private javax.swing.JLabel lblTelefonoEDB;
    private javax.swing.JLabel lblUsuarioI;
    private javax.swing.JPanel panelBuscarBiblio;
    private javax.swing.JPanel panelDatosBiblioBB;
    private javax.swing.JPanel panelDatosBiblioEB;
    private javax.swing.JPanel panelEditarBiblio;
    private javax.swing.JTabbedPane panelEditarDatosBiblio;
    private javax.swing.JPanel panelEliminarBiblio;
    private javax.swing.JPanel panelIngresarDatosBiblio;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelListaBiblio;
    private javax.swing.JTable tblBibliotecas;
    private javax.swing.JTextField txtCodigoBB;
    private javax.swing.JTextField txtCodigoEB;
    private javax.swing.JTextField txtCodigoED;
    private javax.swing.JTextField txtCodigoID;
    private javax.swing.JTextField txtContrasenaAdm;
    private javax.swing.JTextField txtDireccionBB;
    private javax.swing.JTextField txtDireccionEB;
    private javax.swing.JTextField txtDireccionED;
    private javax.swing.JTextField txtDireccionID;
    private javax.swing.JTextField txtNombreBB;
    private javax.swing.JTextField txtNombreEB;
    private javax.swing.JTextField txtNombreED;
    private javax.swing.JTextField txtNombreID;
    private javax.swing.JTextField txtTelefonoBB;
    private javax.swing.JTextField txtTelefonoEB;
    private javax.swing.JTextField txtTelefonoED;
    private javax.swing.JTextField txtTlefonoID;
    private javax.swing.JTextField txtUsuarioAdm;
    // End of variables declaration//GEN-END:variables
}
